# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a65279a5af6717dd5986280fe9043b914743a798b09709f35868419a6c50a69cb2cfdaa60dbfe1b4014c4fe0e7036519f249a46e5d9c870fa96a284a6508204

test:
  secret_key_base: 6f880eb851cfeed60ae09b80f98bdb7e0a3298983f87f40a8d33577600ef5f123a66d1ecf1282f8d782298577b5d91ba37d925b6a8528a73d5c21cc6f33306bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
